# Generated by Django 2.1.3 on 2018-11-20 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя организации')),
                ('description', models.TextField(verbose_name='Детально')),
            ],
            options={
                'verbose_name': 'Организация',
                'verbose_name_plural': 'Организации',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя отдели')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Company')),
                ('supervisor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Начальник')),
                ('workers', models.ManyToManyField(related_name='department_workers', to=settings.AUTH_USER_MODEL, verbose_name='Подчиненные')),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отдели',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя должности')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Company')),
            ],
            options={
                'verbose_name': 'Должност',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('phone', models.CharField(default='87000000000', max_length=14, verbose_name='Номер тел')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('position', models.ManyToManyField(to='task.Position', verbose_name='Должност')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
