# Generated by Django 2.1.3 on 2018-11-20 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя должности')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Department')),
            ],
            options={
                'verbose_name': 'Должност',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Детально'),
        ),
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.ManyToManyField(to='task.Position', verbose_name='Должност'),
        ),
    ]
